### ISSUE TITLE
Adding country selector for phone number field in contact form 

### ISSUE THREAD

**Issue by centurion6x** [yashikabhargava/WebX#122] opened 2022-10-16 14:52 UTC
## Description
In the contact form, current input validation consists of just all numeric conditions. However, adding a country selector will provide better validation and ease of input. 

## Screenshots
Put any screenshot(s) here.
![Screenshot 2022-10-14 at 09-34-26 WebX](https://user-images.githubusercontent.com/80505101/196042213-23f2adb1-1219-4a9b-a860-79a9076d6aa1.png)

## Do you want to work on this issue?
Yes, I do. 

## How are you planning to resolve on this issue?
Some changes to the contact.html form and the validator.js file will help to add necessary elements and logic. 

## Are you raising this issue under hacktoberfest? 
Yes, I'm raising this issue under hacktoberfest.

**Comment by centurion6x** [comment] 2022-10-19 14:35
I just want to confirm that I am actively working on this issue. 😅

**Comment by yashikabhargava** [comment] 2022-10-19 16:57
@centurion6x Yes, Don't worry I'll merge your PR only as the issue is assigned to you.

**Comment by centurion6x** [comment] 2022-10-22 06:41
sorry for the late PR. :pray:

**Closed** 2022-10-23 17:59 UTC
Labels: enhancement, hacktoberfest
